import { test } from "uvu";
import * as assert from "uvu/assert";
import { parseTmpName } from "../src/lib/tmp-parser.ts";

// ---------------------------------------------------------------------------
// Standard format (as generated by the customiser)
// ---------------------------------------------------------------------------

test("parseTmpName - full format with all features", () => {
  // </color><b><color=#FF0000>H</color><color=#00FF00>i</color><color=#AABBCC><color=#DDEEFF></b>
  const input =
    "</color><b><color=#FF0000>H</color><color=#00FF00>i</color><color=#AABBCC><color=#DDEEFF></b>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.letters.length, 2);
  assert.is(result.letters[0].char, "H");
  assert.is(result.letters[0].colour, "#FF0000");
  assert.is(result.letters[1].char, "i");
  assert.is(result.letters[1].colour, "#00FF00");
  assert.is(result.bold, true);
  assert.is(result.colonColour, "#AABBCC");
  assert.is(result.messageColour, "#DDEEFF");
});

test("parseTmpName - grouped letters in single colour tag", () => {
  const input =
    "</color><color=#FFFFFF>Hello</color><color=#AAAAAA><color=#BBBBBB>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.letters.length, 5);
  assert.is(result.letters[0].char, "H");
  assert.is(result.letters[4].char, "o");
  result.letters.forEach((l) => assert.is(l.colour, "#FFFFFF"));
  assert.is(result.bold, false);
  assert.is(result.colonColour, "#AAAAAA");
  assert.is(result.messageColour, "#BBBBBB");
});

test("parseTmpName - no colon or message colour", () => {
  const input = "</color><color=#FF0000>A</color><color=#00FF00>B</color>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.letters.length, 2);
  assert.is(result.colonColour, null);
  assert.is(result.messageColour, null);
});

test("parseTmpName - only colon colour, no message colour", () => {
  const input = "</color><color=#FF0000>X</color><color=#AABBCC>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.letters.length, 1);
  assert.is(result.colonColour, "#AABBCC");
  assert.is(result.messageColour, null);
});

test("parseTmpName - name without leading </color>", () => {
  const input = "<color=#FF0000>A</color><color=#00FF00>B</color>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.letters.length, 2);
  assert.is(result.letters[0].char, "A");
  assert.is(result.letters[0].colour, "#FF0000");
});

test("parseTmpName - 8-digit hex colours (with alpha)", () => {
  const input =
    "</color><color=#FF0000FF>A</color><color=#00FF00AA><color=#BBCCDDEE>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.letters.length, 1);
  assert.is(result.letters[0].colour, "#FF0000FF");
  assert.is(result.colonColour, "#00FF00AA");
  assert.is(result.messageColour, "#BBCCDDEE");
});

test("parseTmpName - bold wrapper detected", () => {
  const input = "</color><b><color=#FFFFFF>X</color></b>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.bold, true);
});

test("parseTmpName - no bold wrapper", () => {
  const input = "</color><color=#FFFFFF>X</color>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.bold, false);
});

// ---------------------------------------------------------------------------
// Real-world example from the screenshot
// ---------------------------------------------------------------------------

test("parseTmpName - real-world multicolour gradient name", () => {
  const input =
    "</color><b><color=#FFE3B3>F</color><color=#FFDAAE>u</color><color=#FFD1AA>e</color><color=#FFC9A5>n</color><color=#FFC2A1>n</color><color=#FFC2CD>a</color><color=#FFE3B3><color=#EEEEEE></b>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.letters.length, 6);
  assert.is(result.letters[0].char, "F");
  assert.is(result.letters[0].colour, "#FFE3B3");
  assert.is(result.letters[5].char, "a");
  assert.is(result.letters[5].colour, "#FFC2CD");
  assert.is(result.bold, true);
  assert.is(result.colonColour, "#FFE3B3");
  assert.is(result.messageColour, "#EEEEEE");
});

// ---------------------------------------------------------------------------
// Graceful fallback cases — should return null
// ---------------------------------------------------------------------------

test("parseTmpName - empty string returns null", () => {
  assert.is(parseTmpName(""), null);
});

test("parseTmpName - whitespace-only string returns null", () => {
  assert.is(parseTmpName("   "), null);
});

test("parseTmpName - plain text name returns null", () => {
  // Just a name without any TMP tags
  assert.is(parseTmpName("Oliver"), null);
});

test('parseTmpName - named colour (color="red") returns null', () => {
  assert.is(parseTmpName('<color="red">Hello</color>'), null);
});

test("parseTmpName - named colour (color=red) returns null", () => {
  assert.is(parseTmpName("<color=red>Hello</color>"), null);
});

test("parseTmpName - rgb colour format returns null", () => {
  assert.is(parseTmpName("<color=rgb(255,0,0)>Hello</color>"), null);
});

test("parseTmpName - malformed unclosed tag without hex returns null", () => {
  assert.is(parseTmpName("<color=>test</color>"), null);
});

test("parseTmpName - unrecognised tags mixed in returns null", () => {
  assert.is(
    parseTmpName(
      "</color><size=20><color=#FF0000>A</color></size><color=#AABBCC>"
    ),
    null
  );
});

test("parseTmpName - random HTML-like tags returns null", () => {
  assert.is(parseTmpName("<div>Hello</div>"), null);
});

test("parseTmpName - incomplete closing tag returns null", () => {
  assert.is(parseTmpName("<color=#FF0000>Hello"), null);
});

test("parseTmpName - only closing colour tag returns null", () => {
  assert.is(parseTmpName("</color>"), null);
});

test("parseTmpName - only unclosed colour tags, no letters returns null", () => {
  assert.is(parseTmpName("<color=#AABBCC><color=#DDEEFF>"), null);
});

test("parseTmpName - text between tags returns null", () => {
  assert.is(parseTmpName("hello<color=#FF0000>A</color>world"), null);
});

test("parseTmpName - bold with no colour tags returns null", () => {
  assert.is(parseTmpName("<b>Hello</b>"), null);
});

test("parseTmpName - case insensitive hex", () => {
  const input = "</color><color=#aaBBcc>X</color><color=#dDeEfF>";
  const result = parseTmpName(input);
  assert.ok(result);
  assert.is(result.letters[0].colour, "#aaBBcc");
  assert.is(result.colonColour, "#dDeEfF");
});

test("parseTmpName - short hex (3 or 5 digits) returns null", () => {
  assert.is(parseTmpName("<color=#F00>X</color>"), null);
  assert.is(parseTmpName("<color=#FF00F>X</color>"), null);
});

test.run();
